### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by amiltonwong** [paulineluc/forecasting_dense_convolutional_features#1]
Hi, @paulineluc ,

I'm very interested in this work and would like to study it further. When will the code be released?

Thx!

**Comment by paulineluc** [comment]
Hi @amiltonwong, just to let you know that we have just released the code in a facebookresearch repo : https://github.com/facebookresearch/instpred
Hope it is useful in your research ! :) Best,

Pauline
